<?php
/**
 * @package     Joomla.Site
 * @subpackage  com_dinning_philosophers
 *
 * @copyright   Copyright (C) 2021 Jesse Riggs. All rights reserved.
 * @license     GNU General Public License version 2 or later;see LICENSE.txt
 */

defined('_JEXEC') or die('Restricted Access');

use Joomla\CMS\Language\Text;

$author = $this->item->created_by_alias;
$title = $this->item->title;
$description = $this->item->metadesc;

?>
<!-- This html was generated by a component generator written by Jesse Riggs. -->
<!-- Begin Dinning_philosophers -->
<div class="item-page">
	<h1>
	<?php echo $title; ?>
	</h1>
	<dl class="article-info">
	 <dt class="article-info-term">—<?php echo $description; ?></dt>
		<dd class="createdby"><?php
			echo Text::_('COM_DINNING_PHILOSOPHERS_BY');
			echo $author; ?></dd>
	</dl>
	<div id="dinning_philosophers-element" style="max-width:100vw;">
		<p><?php echo Text::_('COM_DINNING_PHILOSOPHERS_DINNING_PHILOSOPHERS_DESC'); ?></p>
		<div id="full-screen-container" class="cover" style="margin-right:15px;">
			<div id="dinning-philosophers-container">
				<!-- Put the Konva here --></div>
			<span style="display:flex;position:relative;bottom:30px;">
				<button id="com-dinning-philosophers-step"
					>&#8631;</button>
				<button id="com-dinning-philosophers-algo"
					>&#x2699;</button>
				<button style="right:0;position:absolute;"
					id="com-dinning-philosophers-fullscreen"
					>&#x26F6;</button>
			</span>
		</div>
	</div>
</div>
<!-- End Dinning_philosophers -->
